スピーカーの細かい詳細を追加した
NorikoMizuno/ichiyasaGitSample pull request #2
Opened 2021-06-09 07:23 UTC by Suzuki-Noriko

今回、個人の照会スピーカーに本人と、花火師を追加してみました。

2021-06-09 08:03 UTC, NorikoMizuno requested changes
レビューしたので修正願います。

2021-06-09 08:03 UTC, NorikoMizuno commented on index.html
> +                                <h4>2人目: 花火師・花火　太郎</h4>
花火師はいただけないので他の人にして下さい。

2021-06-10 02:09 UTC, Suzuki-Noriko commented on index.html
> +                                <h4>2人目: 花火師・花火　太郎</h4>
担当者をMicrosoftのGitHub担当の人に変えてみました

2021-06-10 02:10 UTC, Suzuki-Noriko commented on index.html
> +                                <h4>2人目: 花火師・花火　太郎</h4>
担当者をMicrosoftのGitHub担当の人に変えてみました

2021-06-10 02:11 UTC, Suzuki-Noriko commented on index.html
> +                                <h4>2人目: 花火師・花火　太郎</h4>
担当者をMicrosoftのGitHub担当の人に変えてみました

2021-06-10 02:15 UTC, Suzuki-Noriko commented on index.html
> +                                <h4>2人目: 花火師・花火　太郎</h4>
![Uploading image.png…]()

2021-06-10 02:21 UTC, Suzuki-Noriko commented on index.html
> +                                <h4>2人目: 花火師・花火　太郎</h4>
担当者をMicrosoftのGitHub担当の方に変更してみました。

2021-06-10 02:33 UTC, Suzuki-Noriko reviewed
これでいかがでしょうか？
担当を変えてみました。

2021-06-10 02:51 UTC, Suzuki-Noriko commented
プルリクエストを削除します。

2021-06-10 02:51 UTC, closed without merging